---
# server configuration
server:
  port: ${PORT:6666}

# Info
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

# Actuator
management:
  endpoint.shutdown.enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

# Spring config
spring:
  profiles:
    active: native
  sleuth:
    http:
      legacy:
        enabled: true
  application:
    name: ms-config
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:offline-repository/
      #git:
      #  uri: https://github.com/laurentpoirierfr/config-repository # ou bien ==> file://${user.home}/config-repo
    security:
      enabled: false
    bus:
      enabled: true
    discovery:
      enabled: true
    consul:
      host: localhost
      port: 8500
      enabled: true
      config:
        enabled: true


# Logging configuration
logging:
  path: ${LOG_PATH:target}
  file: ${logging.path}/@project.name@-${server.port}.log
# path: ${TEMP}
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    console:  "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"




