---
# server configuration
server:
  port: ${PORT:0}


# Management configuration
management:
  endpoint.shutdown.enabled: true
  security:
    enabled: false # Important en PRODUCTION, a réactiver !!
  context-path: /actuator

spring:
  cloud:
    security:
      enabled: false
    bus:
      enabled: true
    discovery:
      enabled: true
    consul:
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
      host: localhost
      port: 8500
      enabled: true
      config:
        enabled: true


# Logging configuration
logging:
  path: ${LOG_PATH:target}
  file: ${logging.path}/${spring.application.name}-${server.port}.log
# path: ${TEMP}
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    console:  "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

